### ISSUE TITLE
xtide (board rev3) R567 kills fdd bios extension (1.44+1.2M) on xt computer 

### ISSUE THREAD

**Issue by p1plp1** [glitchwrks/xt_ide#3]
I have LONGSHINE LCS-6610F with FDD 1,44 and 1,2MB and without xtIDE 8bit lo-tech rev3 it WORKS without problems.
this FDD controller has onw bios extension at CC00h

when i add XTIDE controller configured at D800h, during boot up process appears FDD CC00h bios extension, it detects 1.44 and 1.2 FDD drives, then D800h XT IDE bios ! IT KILLS FDD BIOS EXTENSION and it is impossible to use HD drives now !!!!!!!!!!!!!

when i try to jumper xtide to address C800h during boot time only XT IDE BIOS appears and fdd controller bios extension at CC00h IS NEVER LOADED!!! 

can u fix this behavior? i have also tested it with R567 xtide i also tried to add SCSI controller and i can see same strange behavior! scsi stops working with xtide too.

**Comment by chapmajs** [comment]
Hi there, the Lo-tech board is not one of our products. You'd be better off contacting the individual or seller that you purchased your board from.
